<a href="https://colab.research.google.com/github/laxhidualopez06/Py---1--Laxhidua/blob/main/MN_U5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EJERCICIO 1 - Tabla de diferencias** --> 27/04/2026

In [ ]:
import numpy as np # importa numpy para manejo de arreglos y operaciones

x  = np.array([1,2,3]) # define los valores de x conocidas
y  = np.array([1,4,9]) # define los valoes de y conocidas

n = len(x) # calcula el numero de puntos

tabla = np.zeros((n,n)) # inicializa la tabla de diferencias divididas

tabla[:,0] = y #llena la primera columna con los valores de y

for j in range(1,n): #itera sobre las columnas de la tabla
    for i in range(n-j): #itera sobre las filas disponibles
        tabla [i,j] = (tabla[i+1,j-1] - tabla[i,j-1]) / (x[i+j] -x[i]) # calcula la diferencia

print("tabla de diferencias dividias : \n" ,tabla)# muestra la tabla

tabla de diferencias dividias : 
 [[1. 3. 1.]
 [4. 5. 0.]
 [9. 0. 0.]]


# **Ejercicio 2** --> 28/04/2026

In [ ]:
import numpy as np # importa numpy para manejo de arreglos y operaciones

x  = np.array([1,2,3]) # define los valores de x conocidas
y  = np.array([1,4,9]) # define los valoes de y conocidas

n = len(x) # calcula el numero de puntos

tabla = np.zeros((n,n)) # inicializa la tabla de diferencias divididas

tabla[:,0] = y #llena la primera columna con los valores de y

for j in range(1,n): #itera sobre las columnas de la tabla
    for i in range(n-j): #itera sobre las filas disponibles
        tabla [i,j] = (tabla[i+1,j-1] - tabla[i,j-1]) / (x[i+j] -x[i]) # calcula la diferencia

def newton_eval(x_data,tabla,x_val): #define funcion para evaluar el polinimio
  n = len(x_data) #numero de puntos
  resultado = tabla[0,0] # inicializa con primer coeficiente

  producto = 1  # inicializa el producto acumulado

  for i in range(1,n): # itera sobre terminos del polinomio
    producto *= (x_val - x_data[i-1]) # calcula el termino (x-x_i)
    resultado += tabla[0,i]*producto # suma el termino correspondiente

  return resultado # retorna valor interpolado

valor = newton_eval(x,tabla,2.5) # evalua el polinomio en x=2.5

print("valor interpolado : ",valor) #muestra resultado




valor interpolado :  6.25


# **Ejercicio 3 - Aplicacion IA : interpolacion de datos** --> 28/04/2026

In [ ]:
import numpy as np # importa

x = np.array([0,1,2,3])
y = np.array([1,2,0,5])

n = len(x) # calcula el numero de puntos

tabla = np.zeros((n,n)) # inicializa la tabla de diferencias divididas

tabla[:,0] = y #llena la primera columna con los valores de y

for j in range(1,n): #itera sobre las columnas de la tabla
    for i in range(n-j): #itera sobre las filas disponibles
        tabla [i,j] = (tabla[i+1,j-1] - tabla[i,j-1]) / (x[i+j] -x[i]) # calcula la diferencia


def newton(x_data,tabla,x_val): #define funcion para evaluar el polinimio
  n = len(x_data) #numero de puntos
  resultado = tabla[0,0] # inicializa con primer coeficiente
  producto = 1

  for i in range(1,n): # itera sobre terminos del polinomio
    producto *= (x_val - x_data[i-1]) # calcula el termino (x-x_i)
    resultado += tabla[0,i]*producto # suma el termino correspondiente

  return resultado

x_interp = 1.5 # punto donde se quiere estimar el valor

y_interp = newton(x,tabla,x_interp) # interpolacion

print("valor estimado : ",y_interp) # resulatdo final


valor estimado :  0.75


# **Ejercicio 1 - implementacion basica de Lagrange**

In [ ]:
import numpy as np # importa

x = np.array([1,2,3]) # Define los puntos conocidos en x
y = np.array([1,4,9]) # Define los valores correspodientes en y

def lagrange(x_data,y_data,x_val):  # define la funcion de interpolacion
  n = len(x_data) # obtiene el numero de puntos
  resultado = 0 #inicializa el resultado del polinomio


  for i in range(n): #itera sobre cada punto
    L = 1 #inicializa del polinomio base L_i

    for j in range(n): #itera sobre todos los puntos para construir L_i
        if j !=i: # evita entre 0 cuando i=j
            L *= (x_val - x_data[j]) / (x_data[i] - x_data[j]) # calcula el

    resultado += y_data[i] * L #acumula el termino correspondiente al polinomio

  return resultado # retorna el valor interpolado

valor = lagrange(x,y,2.5) # evalua el polinomio en x=2.5

print("Valor interpolado : ",valor)


Valor interpolado :  6.25


# **Ejercicio 2 - Comparación con función real**

In [ ]:
import numpy as np  # Importa NumPy

def f(x):  # Define la función real
    return x**2  # Función cuadrática

x = np.array([1,2,3])  # Puntos conocidos
y = f(x)  # Evalúa la función en esos puntos

def lagrange(x_data,y_data,x_val):  # Función de interpolación
    n = len(x_data)  # Número de puntos
    resultado = 0  # Inicializa resultado

    for i in range(n):  # Itera sobre cada punto
        L = 1  # Inicializa polinomio base

        for j in range(n):  # Itera sobre puntos
            if j != i:  # Evita división por cero
                L *= (x_val - x_data[j])/(x_data[i] - x_data[j])  # Calcula término

        resultado += y_data[i]*L  # Suma contribución

    return resultado  # Retorna valor

x_test = 2.5  # Punto de prueba

interp = lagrange(x,y,x_test)  # Valor interpolado

real = f(x_test)  # Valor real

error = abs(real - interp)  # Calcula error

print("Interpolado:", interp)
print("Real:", real)
print("Error:", error)


Interpolado: 6.25
Real: 6.25
Error: 0.0


# **Ejercicio 3 - Aplicación IA reconstrucción de datos**

In [ ]:
import numpy as np  # Importa NumPy

x = np.array([0,1,2,3])  # Datos en x (pueden ser tiempos o features)
y = np.array([1,3,2,5])  # Datos observados (pueden tener ruido)

def lagrange(x_data,y_data,x_val):  # función de interpolación
    n = len(x_data)  # Número de puntos
    resultado = 0  # Inicializa salida

    for i in range(n):  # Itera sobre puntos
        L = 1  # Inicializa polinomio base

        for j in range(n):  # Itera para construir L_i
            if j != i:  # Evita división inválida
                L *= (x_val - x_data[j])/(x_data[i] - x_data[j])  # Calcula término

        resultado += y_data[i]*L  # Acumula resultado

    return resultado  # Retorna valor interpolado

x_interp = 1.5  # Punto donde falta dato

y_interp = lagrange(x,y,x_interp)  # Estima valor faltante

print("Valor estimado:",y_interp)  # Resultado


Valor estimado: 2.4375


Permite construir modelos exactos apartir de datos, es intuitiva y directa, util en dataset pequeños base para métodos más avanzados

## **Ejercicio 1 - Interpolación segmentada(Spline)** --> 07/05/2026

In [ ]:
import numpy as np # importa numpy para manejo de datos numericos
from scipy.interpolate import CubicSpline # importa el metodo de spline cubico

x = np.array([0,1,2,3]) # Define los puntos en el eje x
y = np.array([1,3,2,5]) # Define los valores correspondientes

spline = CubicSpline(x,y) # Construye el spline cubico

x_interp = np.linspace(0,3,100) # Genera 100 puntos para evaluacion

y_interp = spline(x_interp) # Evalua el spline en los puntos de interpolacion

print("valores interpolados : ",y_interp) # Muestra los valores


valores interpolados :  [1.         1.17220877 1.33542959 1.48985725 1.63568653 1.77311221
 1.90232908 2.02353192 2.13691553 2.24267468 2.34100416 2.43209877
 2.51615327 2.59336246 2.66392112 2.72802404 2.78586601 2.8376418
 2.88354621 2.92377401 2.95852    2.98797896 3.01234568 3.03181494
 3.04658152 3.05684021 3.0627858  3.06461307 3.06251681 3.0566918
 3.04733283 3.03463468 3.01879215 3.         2.97845303 2.95434603
 2.92787378 2.89923106 2.86861266 2.83621337 2.80222797 2.76685125
 2.73027799 2.69270297 2.65432099 2.61532682 2.57591526 2.53628108
 2.49661908 2.45712404 2.41799074 2.37941397 2.34158852 2.30470917
 2.2689707  2.2345679  2.20169556 2.17054846 2.14132139 2.11420913
 2.08940646 2.06710818 2.04750907 2.03080391 2.01718749 2.00685459
 2.         1.99681851 1.99750489 2.00225394 2.01126045 2.02471918
 2.04282494 2.06577251 2.09375667 2.1269722  2.1656139  2.20987654
 2.25995492 2.31604382 2.37833802 2.44703231 2.52232147 2.60440029
 2.69346356 2.78970606 2.89332257 3.0045

# **Ejercicio 2 -Regresión Lineal** --> 07/05/2026\

In [ ]:
import numpy as np  # Importa NumPy

x = np.array([1,2,3,4,5])  # Datos de entrada
y = np.array([2,4,5,4,5])  # Datos observados

coef = np.polyfit(x,y,1)   # Ajusta un polinomio de grado 1 (recta)

m = coef[0]   # Pendiente de la recta
b = coef[1]   # Intersección con el eje y

y_pred = m*x + b  # Calcula los valores predichos por el modelo

print("Pendiente:",m)      # Muestra la pendiente
print("Intercepto:",b)     # Muestra el término independiente
print("Predicción:",y_pred) # Muestra los valores estimados

Pendiente: 0.6000000000000001
Intercepto: 2.1999999999999997
Predicción: [2.8 3.4 4.  4.6 5.2]


# **Ejercicio 3 -Correlación** --> 07/05/2026

In [ ]:
import numpy as np # importa numpy

x = np.array([1,2,3,4,5]) # Datos de variable independiente
y = np.array([2,4,5,4,5]) # Datos de variable independiente

correlacion = np.corrcoef(x,y)[0,1] # Calcula la correlación

print("Correlación:",correlacion) #Muestra resultado

Correlación: 0.7745966692414834


In [ ]:
import numpy as np  # Importa la biblioteca NumPy para cálculos matriciales

x = np.array([1, 2, 3, 4, 5])  # Define los datos de entrada
y = np.array([2, 4, 5, 4, 5])  # Define los datos observados

X = np.vstack([np.ones(len(x)), x]).T  # Construye la matriz de diseño con columna de unos y val

XT = X.T  # calcula la transpuesta de la matriz X

beta = np.linalg.inv(XT.dot(X)).dot(XT).dot(y)  # Aplica la fórmula de mínimos cuadrados

b = beta[0]  # Extrae el intercepto
m = beta[1]  # Extrae la pendiente

y_pred = m*x + b  # Calcula los valores estimados por el modelo

print("Pendiente:", m)     # Muestra la pendiente
print("Intercepto:", b)    # Muestra el intercepto
print("Predicción:", y_pred)  # Muestra los valores ajustados

# Construye la matriz de diseño con columna de unos y valores de x

Pendiente: 0.6000000000000002
Intercepto: 2.2000000000000046
Predicción: [2.8 3.4 4.  4.6 5.2]


In [ ]:
import numpy as np  # Importa NumPy

x = np.array([1,2,3,4,5])    # Datos de entrada
y = np.array([2,4,5,4,5])    # Datos observados

coef = np.polyfit(x,y,2)     # Ajusta un polinomio de grado 2

a = coef[0]    # Coeficiente cuadrático
b = coef[1]    # Coeficiente lineal
c = coef[2]    # Término independiente

y_pred = a*x**2 + b*x + c    # Calcula valores predichos

print("Coeficientes:",coef)  # Muestra coeficientes
print("Predicción:",y_pred)  # Muestra ajuste

Coeficientes: [-0.28571429  2.31428571  0.2       ]
Predicción: [2.22857143 3.68571429 4.57142857 4.88571429 4.62857143]


In [ ]:
import numpy as np  # Importa NumPy

x = np.array([1,2,3,4,5])  # Datos de entrada
y = np.array([2,4,5,4,5])  # Datos reales

coef = np.polyfit(x,y,1)   # Ajuste Lineal

y_pred = coef[0]*x + coef[1]  # Predicciones

error = np.mean((y - y_pred)**2)  # Calcula el error cuadrático medio

print("Error MSE:",error)  # Muestra el error


Error MSE: 0.47999999999999987
